version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: pasarela_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: pasarela_user
      POSTGRES_PASSWORD: pasarela_password
      POSTGRES_DB: pasarela_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: